---
title: Walking through the delta method
author: ''
date: '2020-07-06'
categories:
  - math
tags:
  - discoveryfiction
slug: walking-through-the-delta-method
---

Imagine we've constructed an estimator $T_n$ for some parameter $\theta$ but what we really want to know about is $\phi(\theta)$, some transformation of the parameter.

Can we use our knowledge of the behavior of $T_n$ to learn about $\phi(T_n)$?

By the **continuous-mapping theorem** if $\phi$ is continuous then:
  
  * if $T_n \to \theta$
  * then $\phi(T_n) \to \phi(\theta)$
  
By the **delta method** we have

* if $\sqrt{n}(T_n - \theta) \rightsquigarrow T$ as $n \to \infty$
* then $\sqrt{n}(\phi(T_n) - \phi(\theta)) \rightsquigarrow \phi'_\theta(T)$

where $\phi'_\theta(T) = \phi'(\theta)*T$.

# Wishful Thinking About the Delta Method: If $\phi$ were linear

I found the result of the delta method a bit strange. If I had to immediately guess the result it would be:

$$\sqrt{n}(\phi(T_n) - \phi(\theta)) \rightsquigarrow \phi(T)$$

not $$\rightsquigarrow \phi'_\theta(T).$$

When WOULD this be true? Well if $\phi$ were defined to be a linear function then by linearity:

$$\sqrt{n}(\phi(T_n) - \phi(\theta)) = \phi(\sqrt{n}(T_n - \theta)) \rightsquigarrow \phi(T)$$

with the last convergence by the continuous mapping theorem.

But the delta method applies to more than just linear functions $\phi$ so what's the next logical step?

We should approximate the function $\phi$ by something linear: the natural candidate is **the derivative**; it's linear and it approximates.

Let's do that drop in replacement:

$$\sqrt{n}(\phi(T_n) - \phi(\theta)) = \sqrt{n}(\phi'_\theta(T_n) - \phi'_\theta(\theta)) = \phi'_\theta(\sqrt{n}(T_n - \theta)) \rightsquigarrow \phi'_\theta(T)$$

Now we just need to make sure that our approximation is good.

# $o$-definition of the derivative.

The definition of the derivative we're using is

$$R_\theta(h) = \phi(\theta + h) - \phi(\theta)- \phi'_\theta(h) = o(h) \quad h \to 0  $$

we then take $h = T_n - \theta$

$$R = \phi(T_n) - \phi(\theta) - \phi'_\theta(T_n - \theta) = o(T_n - \theta
)$$

That is our remainder converges to $0$ faster than $||T_n - \theta||$ converges to $0$.

We then multiply both sides by $\sqrt{n}$ and we have:

$$\sqrt{n}(\phi(T_n) - \phi(\theta)) - \sqrt{n}\phi'_\theta(T_n - \theta) = o(r_n(T_n - \theta)) = o(O(\sqrt{n}(T_n- \theta)) = o(O(1)) = o(1)$$

Then by Slutsky's theorem we have that 

$$\sqrt{n}(\phi(T_n) - \phi(\theta)) \rightsquigarrow \phi'_\theta(T) + 0 $$