---
title: MLE + Hessian Computations
author: Stone Chen
date: '2020-06-30'
categories: []
tags: []
---


# mle and hessian computations

# A formula for the determinant of a compound symmetric covariance matrix

$$\begin{aligned}
\Sigma&=\left|\begin{array}{cccc}
\sigma_{11}^{2} & \rho \sigma_{1} \sigma_{2} & \cdots & \rho \sigma_{1} \sigma_{p} \\
\rho \sigma_{2} \sigma_{1} & \sigma_{22}^{2} & \cdots & \rho \sigma_{2} \sigma_{p} \\
\vdots & \vdots & \ddots & \vdots \\
\rho \sigma_{p} \sigma_{1} & \cdots & \cdots & \sigma_{p p}^{2}
\end{array}\right|\\
&=\left|\begin{array}{ccccc}
1 & \sigma_{1} & \sigma_{2} & \cdots & \sigma_{p} \\
0 & \sigma_{11}^{2} & \rho \sigma_{1} \sigma_{2} & \cdots & \rho \sigma_{1} \sigma_{p} \\
0 & \rho \sigma_{2} \sigma_{1} & \sigma_{22}^{2} & \cdots & \rho \sigma_{2} \sigma_{p} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & \rho \sigma_{p} \sigma_{1} & \cdots & \cdots & \sigma_{p p}^{2}
\end{array}\right|\\
&=\left|\begin{array}{ccccc}
1 & \sigma_{1} & \sigma_{2} & \cdots & \sigma_{p} \\
-\rho \sigma_{1} & \sigma_{11}^{2}(1-\rho) & 0 & \cdots & 0 \\
-\rho \sigma_{2} & 0 & \sigma_{22}^{2}(1-\rho) & 0 & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
-\rho \sigma_{p} & 0 & 0 & 0 & \sigma_{p p}^{2}
\end{array}\right|\\
&=\left| \begin{array}{ccccc}
1+\sum_{i=1}^{p} \frac{\rho}{(1-\rho)} &\sigma_{1} & \sigma_{2} & \cdots & \sigma_{p} \\
0 & \sigma_{11}^{2}(1-\rho) & 0 & \cdots & 0 \\
0 & 0 & \sigma_{22}^{2}(1-\rho) & 0 & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & 0 & \sigma_{p p}^{2}
\end{array}\right|\\
&=\left(1+\sum_{i=1}^{p} \frac{\rho}{(1-\rho)}\right)\left((1-\rho)^{p} \prod_{i=1}^{p} \sigma_{i i}^{2}\right)
\end{aligned}$$

## Steps

The goal is to put the matrix into an upper triangular format. That way we can directly read off the determinant value.

We add an additional row and column (does not change determinant)

Multiply new first row by $-\rho\sigma_1$ then add to second row etc. to eliminate off-diagonals on each row (minus first column)

Then proceed to multiply second column by $\frac{\rho}{\sigma_1(1-\rho)}$ and add to first column (eliminate off diagonals of first column)

Take product of diagonals

# The inverse of the compound symmetric covariance matrix

$$\begin{aligned}
\left(\begin{array}{cccc}
\sigma & \rho & \cdots & \rho \\
\rho & \sigma & \cdots & \rho \\
\vdots & \vdots & \ddots & \vdots \\
\rho & \rho & \cdots & \sigma
\end{array}\right)^{-1} &=\left((\sigma-\rho) \mathbf{I}_{n}+\rho \mathbf{J}_{n}\right)^{-1} \\
&=\frac{1}{\sigma-\rho}\left(\mathbf{I}_{n}+\frac{\rho}{\sigma-\rho} \mathbf{J}_{n}\right)^{-1} \\
&=\frac{1}{\sigma-\rho} \sum_{i=0}^{\infty}(-1)^{i}\left(\frac{\rho}{\sigma-\rho} \mathbf{J}_{n}\right)^{i} \\
&=\frac{1}{\sigma-\rho} \sum_{i=0}^{\infty}(-1)^{i}\left(\frac{\rho}{\sigma-\rho}\right)^{i} n^{i-1} \mathbf{J}_{n} \\
&=\frac{1}{\sigma-\rho}\left(\mathbf{I}_{n}+\sum_{i=1}^{\infty}(-1)^{i}\left(\frac{\rho}{\sigma-\rho}\right)^{i} n^{i-1} \mathbf{J}_{n}\right) \\
&=\frac{1}{\sigma-\rho}\left(\mathbf{I}_{n}-\frac{\rho}{\sigma-\rho} \sum_{i=1}^{\infty}(-1)^{i-1}\left(\frac{\rho}{\sigma-\rho}\right)^{i-1} n^{i-1} \mathbf{J}_{n}\right) \\
&=\frac{1}{\sigma-\rho}\left(\mathbf{I}_{n}-\frac{\rho}{\sigma-\rho} \sum_{i=0}^{\infty}(-1)^{i}\left(\frac{\rho}{\sigma-\rho}\right)^{i} n^{i} \mathbf{J}_{n}\right) \\
&=\frac{1}{\sigma-\rho}\left(\mathbf{I}_{n}-\frac{\rho}{\sigma-\rho} \frac{1}{1+\frac{n \rho}{\sigma-\rho}} \mathbf{J}_{n}\right) \\
 &=\frac{1}{\sigma-\rho}\left(\mathbf{I}_{n}-\frac{\rho}{\sigma-\rho+n \rho} \mathbf{J}_{n}\right) \\
&=\frac{1}{\sigma-\rho}\left(\mathbf{I}_{n}-\frac{\rho}{\sigma+(n-1) \rho} \mathbf{J}_{n}\right)
\end{aligned}$$

# Full likelihood model

Consider trivariate normal:
$$ Y=\left(\begin{array}{c}
Y_{1} \\
Y_{2} \\
Y_{3}
\end{array}\right) \sim N\left(\left(\begin{array}{c}
\mu_{1} \\
\mu_{2} \\
\mu_{3}
\end{array}\right), \quad \mathrm{V}\right)\\ \text { where } \mathrm{V}=\sigma^{2}\left(\begin{array}{ccc}
1 & \rho & \rho \\
\rho & 1 & \rho \\
\rho & \rho & 1
\end{array}\right)$$

## Full likelihood 

$$\begin{aligned}
-2ll &=\log |V|+(Y-\mu)^{T} V^{-1}(Y-\mu) \\
 &=\ln \left(\sigma^{2}(1+2 \rho)(1-\rho)^{2}\right)+\tilde{Y}^{T} \frac{1}{\sigma^{2}(1-\rho)}\left(\mathbf{I}_{3}-\frac{\rho}{1+2 \rho} \mathbf{J}_{3}\right) \tilde{Y} \\
 &=\ln \left(\sigma^{2}(1+2 \rho)(1-\rho)^{2}\right)+\frac{\tilde{Y}^{T} \tilde{Y}}{\sigma^{2}(1-\rho)}+\frac{1}{\sigma^{2}(1-\rho)} \frac{\rho}{1+2 \rho} \tilde{Y}^{T} \mathbf{J}_{3} \tilde{Y} \\
 &=\ln \left(\sigma^{2}\right)+\ln (1+2 \rho)+2 \ln (1-\rho)+\frac{\tilde{Y}^{T} \tilde{Y}}{\sigma^{2}(1-\rho)}+\frac{\rho \tilde{Y}^{T} \mathbf{J}_{3} \tilde{Y}}{\sigma^{2}\left(1+\rho-2 \rho^{2}\right)} 
\end{aligned}$$
where:

$$\begin{aligned} \det(V)&=\sigma^{2} \det\left(\begin{array}{lll}
1 & p & p \\
\rho & 1 & \rho \\
\rho & \rho & 1
\end{array}\right)\\
&=\sigma^{2}(1+2 \rho)(1-\rho)^{2} \end{aligned}$$

$$V^{-1}=\frac{1}{\sigma^{2}}\left(\begin{array}{ccc}
1 & \rho & \rho \\
\rho & 1 & \rho \\
\rho & \rho & 1
\end{array}\right)^{-1}$$
$$=\frac{1}{\sigma^{2}} \frac{1}{1-\rho}\left(I_{3}-\frac{\rho}{1+2 \rho} J_{3}\right)$$


## Gradients

$$\begin{aligned}\frac{\partial(-2 l l)}{\partial\left(\sigma^{2}\right)} &=\frac{1}{\sigma^{2}}-\frac{\tilde{Y}^{T} \tilde{Y}}{\sigma^{4}(1-\rho)}-\frac{\rho}{\sigma^{4}\left(1+\rho-2 \rho^{2}\right)} \tilde{Y}^{T} \mathbf{J}_{3} \tilde{Y} \\
\frac{d(-2 l l)}{d \rho} &=\frac{2}{1+2 \rho}-\frac{2}{1-\rho}-\frac{\tilde{Y}^{T} \tilde{Y}}{\sigma^{2}(1-\rho)}+\frac{1+2 \rho^{2}}{\sigma^{2}\left(1+\rho-2 \rho^{2}\right)^{2}} \tilde{Y}^{T} \mathbf{J}_{3} \tilde{Y} \end{aligned}$$

## Hessians
$$\begin{aligned}
\frac{d^{2}(-2 l l)}{d\left(\sigma^{2}\right)^{2}} &=-\frac{1}{\sigma^{4}}+\frac{2 \tilde{Y}^{T} \tilde{Y}}{\sigma^{6}(1-\rho)}+\frac{2 \rho}{\sigma^{6}\left(1+\rho-2 \rho^{2}\right)} \tilde{Y}^{T} \mathbf{J}_{3} \tilde{Y} \\
\frac{d^{2}(-2 l l)}{d\left(\sigma^{2}\right) d \rho} &=\frac{\tilde{Y}^{T} \tilde{Y}}{\sigma^{4}(1-\rho)^{2}}-\frac{1+2 \rho^{2}}{\sigma^{4}\left(1+\rho-2 \rho^{2}\right)^{2}} \tilde{Y}^{T} \mathbf{J}_{3} \tilde{Y} \\
\frac{d^{2}(-2 l l)}{d \rho^{2}} &=\frac{-4}{(1+2 \rho)^{2}}+\frac{2}{(1-\rho)^{2}}+\frac{\tilde{Y}^{T} \tilde{Y}}{\sigma^{2}(1-\rho)^{2}}+\frac{2\left(4 \rho^{3}+6 \rho-1\right)}{\sigma^{2}\left(1+\rho-2 \rho^{2}\right)^{3}} \tilde{Y}^{T} \mathbf{J}_{3} \tilde{Y} \end{aligned}$$


$$\operatorname{mle}\left(\sigma^{2}\right)=\widehat{\sigma^{2}}=\frac{2 \tilde{Y}^{T} \tilde{Y}}{1-\rho}+\frac{2 \rho \tilde{Y}^{T} J_{3} \tilde{Y}}{1+\rho-2 \rho^{2}}$$

# Pairwise model

Let $$\tilde{Y}_{i j}=\left(\begin{array}{l}Y_{i}-\mu_{i} \\ Y_{j}-\mu_{j}\end{array}\right),$$

and let 

$$l l_{i j}$$ be the log-likelihood of $\tilde{Y}_{i j}$ then pairwise likelihood of $\tilde{Y}$ is
$$l l_{p}=l l_{12}+l l_{13}+l l_{13} $$


## pairwise likelihood
$$\begin{aligned} -2 l l_{i j} & =\log |V|+\widetilde{Y_{i j}}^{T} V^{-1} \widetilde{Y_{i j}} \\
&=\ln \left(\sigma^{2}\left(1-\rho^{2}\right)\right)+\tilde{Y}_{ij}^{T} \frac{1}{\sigma^{2}(1-\rho)}\left(\mathbf{I}_{2}-\frac{\rho}{1+\rho} \mathbf{J}_{2}\right) \tilde{Y}_{i j} \\
&=\ln \left(\sigma^{2}\right)+\ln (1+\rho)+\ln (1-\rho)+\frac{\tilde{Y}_{i j}^{T} \tilde{Y}_{i j}}{\sigma^{2}(1-\rho)}+\frac{\rho \widetilde{Y}_{i j}^{T} \mathbf{J}_{3} \widetilde{Y}_{i j}}{\sigma^{2}\left(1-\rho^{2}\right)} \end{aligned}$$
$$\begin{aligned}
\det\left(V_{12}\right)&=\sigma^{2} \det\left(\begin{array}{cc}
1 & \rho \\
\rho & 1
\end{array}\right)\\
&=\sigma^{2}\left(1-\rho^{2}\right)\end{aligned}$$
where:
$$ \begin{aligned}
V^{-1}&=\frac{1}{\sigma^{2}}\left(\begin{array}{ccc}
1 & \rho & \rho \\
\rho & 1 & \rho \\
\rho & \rho & 1
\end{array}\right)^{-1}\\
&=\frac{1}{\sigma^{2}} \frac{1}{1-\rho}\left(I_{2}-\frac{\rho}{1+\rho} J_{2}\right) \\
\end{aligned}$$


## Gradients


$$\begin{aligned}
\frac{d\left(-2 l l_{i j}\right)}{d\left(\sigma^{2}\right)}&=\frac{1}{\sigma^{2}}-\frac{\tilde{Y}_{i j}^{T} \tilde{Y}_{i j}}{\sigma^{4}(1-\rho)}-\frac{\rho \widetilde{Y_{l}}^{T} \mathbf{J}_{3} \widetilde{Y}_{i j}}{\sigma^{4}\left(1-\rho^{2}\right)} \\
\frac{d\left(-2 l l_{i j}\right)}{d \rho}&=\frac{1}{1+\rho}-\frac{1}{1-\rho}-\frac{\tilde{Y}_{i j}^{T} \tilde{Y}_{i j}}{\sigma^{2}(1-\rho)^{2}}+\frac{1+\rho^{2}}{\sigma^{2}\left(1-\rho^{2}\right)^{2}} \widetilde{Y_{i j}}^{T} \mathbf{J}_{3} \widetilde{Y_{ij}} \end{aligned}$$


## Hessians

$$\begin{aligned}
\frac{d^{2}\left(-2 l l_{i j}\right)}{d\left(\sigma^{2}\right)^{2}} &=-\frac{1}{\sigma^{4}}+\frac{-2 \tilde{Y}_{i j}^{T} \tilde{Y}_{i j}}{\sigma^{6}(1-\rho)}+\frac{2 \rho \widetilde{Y}_{ij}^{T} \mathbf{J}_{3} \widetilde{Y}_{ij}}{\sigma^{6}\left(1-\rho^{2}\right)} \\
\frac{d^{2}\left(-2 l l_{i j}\right)}{d\left(\sigma^{2}\right) d \rho} &=\frac{\tilde{Y}_{i j}^{T} \tilde{Y}_{i j}}{\sigma^{4}(1-\rho)^{2}}-2 \frac{1+\rho^{2}}{\sigma^{4}\left(1-\rho^{2}\right)^{2}} \widetilde{Y_{ij}}^{T} \mathbf{J}_{3} \widetilde{Y_{i j}} \\
\frac{d^{2}\left(-2 l l_{i j}\right)}{d \rho^{2}} &=-\frac{1}{(1+\rho)^{2}}+\frac{1}{(1-\rho)^{2}}+\frac{2 \tilde{Y}_{i j}^{T} \tilde{Y}_{i j}}{\sigma^{2}(1-\rho)^{3}}+2 \frac{\rho-\rho^{3}+2 \rho^{4}}{\sigma^{2}\left(1-\rho^{2}\right)^{3}} \widetilde{Y}_{ij}^{T} \mathbf{J}_{3} \widetilde{Y_{ij}}
\end{aligned}$$


$$\begin{aligned}
\frac{d^{2}\left(-2 l l_{p}\right)}{d\left(\sigma^{2}\right)^{2}} &=-\frac{3}{\sigma^{4}}+\frac{-2 A}{\sigma^{6}(1-\rho)}+\frac{2 \rho B}{\sigma^{6}\left(1-\rho^{2}\right)} \\
\frac{d^{2}\left(-2 l l_{p}\right)}{d\left(\sigma^{2}\right) d \rho}&= \frac{A}{\sigma^{4}(1-\rho)^{2}}-2 \frac{1+\rho^{2}}{\sigma^{4}\left(1-\rho^{2}\right)^{2}} B \\
\frac{d^{2}\left(-2 l l_{p}\right)}{d \rho^{2}}&=-\frac{3}{(1+\rho)^{2}}+\frac{3}{(1-\rho)^{2}}+\frac{2 A}{\sigma^{2}(1-\rho)^{3}}+2 \frac{\rho-\rho^{3}+2 \rho^{4}}{\sigma^{2}\left(1-\rho^{2}\right)^{3}} B \\
\end{aligned}$$

where:

$$\begin{aligned} A&=\tilde{Y}_{12}^{\top} \tilde{Y}_{12}+\tilde{Y}_{13}^{\top} \tilde{Y}_{13}+\tilde{Y}_{23}^{\top} \tilde{Y}_{23} \\
 B&=\tilde{Y}_{12}^{\top} \mathbf{J}_{2} \tilde{Y}_{12}+\tilde{Y}_{13}^{\top} \widetilde{\mathbf{J}}_{2} Y_{13}+\tilde{Y}_{23}^{\top} \mathbf{J}_{2} \tilde{Y}_{23}\end{aligned}$$
 
 $$m l e\left(\sigma^{2}\right)_{p a i r w i s e}=\sigma^{2}=\frac{-2 \tilde{Y}_{i j}^{T} \tilde{Y}_{i j}}{(1-\rho)}+\frac{2 \rho \widetilde{Y_{ij}}^T \mathbf{J}_{3} \widetilde{Y_{ij}}}{(1-p)(1+p)}$$